### PR TITLE
Smoke artifact & CI job

### PR DESCRIPTION
**Pull request by gares**
(includes useful commit from v8.13)

### CODE REVIEW

**Comment by gares** [comment]
apparently osx's bash is old (v3, which does not know -A)

**Comment by gares** [comment]
@MSoegtropIMC I Need help on osx, it seems I don't get to use bash in the smoke kit script. Otherwise the PR seems fine to me

**Comment by MSoegtropIMC** [comment]
@gares: yes, afaik macOS doesn't include GPL3 stuff. The default is zsh. Since the script uses arrays it isn't easy to port it to plain posix, but likely not impossible either. Zsh should work, though, possibly with slightly modified syntax. I should have used Python right away ...

**Comment by gares** [comment]
I fixed it by installing bash via brew on osx

**Pull request merged**
