### PR TITLE
Create a debugger preview

### PR DESCRIPTION
**Pull request by jfehrle**
When I run the script to create the switch, it dies after about 2 minutes and > 10000 lines of output.  Hard to tell what might be wrong.

Do I have the new opam files in the right place and with acceptable names (i.e. `coq.debugger`, `coqide.debugger`, `2021.debugger`)?

Attn: @Zimmi48 @MSoegtropIMC

### CODE REVIEW

**Comment by Zimmi48** [comment]
Hard to tell what might be wrong by just looking at the code too.
My only remark is that maybe opam doesn't like a version name like "debugger". You could use something like "8.14~debugger" or "8.14.dev~debugger". The ".dev" might be important for opam to understand that it's a branch and therefore can receive update.
All these remarks should be taken with a grain of salt given that I'm not a big opam user.

Can you post the log in an attachment?

**Comment by jfehrle** [comment]
You mean ` 8.14~debugger` or `8.14.dev~debugger` rather than strikeout type?

**Comment by jfehrle** [comment]
Got it.  Diverting stdout to a file makes it possible to see the error messages:

```
$ time bash coq_platform_make.sh >log
Install full platform (f), Coq base (b) or Coq+CoqIDE (i)? (f/b/i/c=cancel) i
Build opam packages parallel (p) or sequential (s)? (p/s/c=cancel) p
Number of parallel make jobs (number in 1..16) 12
Shall the existing switch be kept (k) or deleted (d) ? (k/d/c=cancel) d
[NOTE] These are the repositories in use by the current switch. Use '--all' to see all configured repositories.
# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
# The following system packages are needed:
# All required OS packages found.
[ERROR] Package coq has no version 8.15.0.dev.
[ERROR] Package coqide has no version 8.15.0.dev.

real    1m59.792s
user    6m6.929s
sys     0m33.167s
```

Looks like I added the opam files in the wrong directory.  They should be, for example, `platform/opam/packages/coq/coq.8.15.0.dev/opam`, not `platform/tree/2021.03/opam/packages/coq/coq.8.15.0.dev/opam`.

**Comment by jfehrle** [comment]
That works if I only build coq+coqide.  A full build fails.  I see some errors in the output.  Will look at them in the morning.

**Comment by Zimmi48** [comment]
> You mean ` 8.14~debugger` or `8.14.dev~debugger` rather than strikeout type?

Yes, I wrote this on my phone without realizing that I was using markup.

**Comment by Zimmi48** [comment]
> That works if I only build coq+coqide. A full build fails. I see some errors in the output. Will look at them in the morning.

OK, disabling the packages that fail should be the easiest solution.

**Comment by jfehrle** [comment]
If it were only that simple.  A full build of the vanilla Coq v8.14 branch fails with messages similar to this version that also has my debugger changes:  `git+https://github.com/jfehrle/coq#debugger_preview`.   I get a number of failures, including some things in the standard library.  It looks like the build script is getting confused about which compiler version (switch) to use to create the new switch.  The strings `4.06.0` and `4.06.0+spacetime` appear in many places in the log, more than `4.07.1`, which is what I wanted.

I see 4-5 Coq library files with this failure:

```
  1536	File "./theories/MSets/MSetList.v", line 893, characters 0-20:
  1537	Warning: Removed file ./theories/MSets/MSetList.vo
  1538	Error: Native compiler failed with error: Invalid argument
```

plus a segmentation fault compiling `theories/Strings/Byte.v`!  And shortly below:

`  1565	make[1]: Leaving directory '/home/jfehrle/.opam/4.06.0+spacetime/.opam-switch/build/coq.8.11.2'`

If I change the depenency in `platform/opam/packages/coq/coq.8.15.0.dev/opam` to `"ocaml" {>= "4.07.0"}`, I get this error:

```
===== INSTALL OPAM PACKAGES (PARALLEL) =====
The following dependencies couldn't be met:
  - coq-simple-io → coq < 8.14~ → ocaml < 4.06.0
      base of this switch (use `--unlock-base' to force)
Your request can't be satisfied:
  - No available version of coq satisfies the constraints

No solution found, exiting
```

```
$ opam switch
#  switch                                compiler                                   description
   /home/jfehrle/.opam/4.06.0                                                       /home/jfehrle/.opam/4.06.0
   /mnt/c/proj/ocaml                                                                /mnt/c/proj/ocaml
   4.06.0                                ocaml-base-compiler.4.06.0                 4.06.0
   4.06.0+spacetime                      ocaml-variants.4.06.0+spacetime            4.06.0+spacetime
   4.06.0+statistical-memprof            ocaml-variants.4.06.0+statistical-memprof  4.06.0+statistical-memprof
   4.06.1+statistical-memprof            ocaml-variants.4.06.1+statistical-memprof  4.06.1+statistical-memprof
   4.07.1                                ocaml-base-compiler.4.07.1                 4.07.1
   4.11.1                                ocaml-base-compiler.4.11.1                 4.11.1
   4.12.0                                ocaml-base-compiler.4.12.0                 4.12.0
   _coq-platform_.2021.02.1              ocaml-base-compiler.4.07.1                 _coq-platform_.2021.02.1
   _coq-platform_.2021.03.0              ocaml-base-compiler.4.07.1                 _coq-platform_.2021.03.0
   _coq-platform_.2021.814               ocaml-base-compiler.4.07.1                 _coq-platform_.2021.814
   _coq-platform_.2021.debugger          ocaml-base-compiler.4.07.1                 _coq-platform_.2021.debugger
→  _coq-platform_.8.14+debugger_preview  ocaml-base-compiler.4.07.1                 _coq-platform_.8.14+debugger_preview
```
[log.pvfull.txt](https://github.com/coq/platform/files/7026282/log.pvfull.txt)

**Comment by jfehrle** [comment]
It seems to me that the platform hasn't been configured for V8.14.  Who would normally handle that?  Perhaps they would be willing to configure it or tell me how to go about it.

**Comment by MSoegtropIMC** [comment]
Since this is part of the 8.15 preview, I will close this PR.

**Pull request closed without merging**
