### PR TITLE
Experiment

### PR DESCRIPTION
**Pull request by jfehrle**

### CODE REVIEW

**Comment by jfehrle** [comment]
@MSoegtropIMC Do you have any idea why the windows 64 build for 8.16 is failing?  I certainly didn't touch `coqdoc`.  I cherry picked my modified fix on top of the `v8.16` tag before generating the path.  Thanks.

```
    59	File "tools/coqdoc/dune", line 16, characters 7-11:
    60	16 |  (name main)
    61	            ^^^^
    62	(cd _build/default && C:\cygwin_coq_platform\home\runneradmin\.opam\__coq-platform.2022.09.0~8.16~2022.09~beta1\bin\ocamlopt.opt.exe -w -40 -rectypes -g -O3 -unbox-closures -o tools/coqdoc/main.exe C:/cygwin_coq_platform/home/runneradmin/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/ocaml\str.cmxa -I C:/cygwin_coq_platform/home/runneradmin/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/ocaml config/config.cmxa boot/boot.cmxa C:/cygwin_coq_platform/home/runneradmin/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/ocaml\unix.cmxa -I C:/cygwin_coq_platform/home/runneradmin/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/ocaml C:/cygwin_coq_platform/home/runneradmin/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/ocaml\threads\threads.cmxa -I C:/cygwin_coq_platform/home/runneradmin/.opam/__coq-platform.2022.09.0~8.16~2022.09~beta1/lib/ocaml clib/clib.cmxa tools/coqdoc/.main.eobjs/native/dune__exe.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Cdglobals.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Alpha.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Index.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Tokens.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Output.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Cpretty.cmx tools/coqdoc/.main.eobjs/native/dune__exe__FileUtil.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Glob_file.cmx tools/coqdoc/.main.eobjs/native/dune__exe__LatexCompiler.cmx tools/coqdoc/.main.eobjs/native/dune__exe__Main.cmx)
    63	** Fatal error: Cannot run cygpath -m "libgcc" "libgcc.lib" "libgcc.dll.a" "libgcc.a" 
```

The code I added is to just to convince me that the patch is indeed included in the build:
```
    try
      let fname = Filename.concat (Filename.get_temp_dir_name ())
          (Printf.sprintf "CREATE_FILE_%d" (!Shared.cvt_pid (Unix.getpid ()))) in
      let fd = open_out fname in
      close_out fd
    with _ -> ();
```

**Comment by MSoegtropIMC** [comment]
@jfehrle : the actual error is `Fatal error: Cannot run cygpath -m "libgcc" "libgcc.lib" "libgcc.dll.a" "libgcc.a"`. This looks like an intemittent cygwin hickup - this happens rarely (say one in a few 100) but it happens. I would rerun.

As I said you would save you a lot of time (and a bit of CO2) if you would change `-extent=x` to `-extent=i` in all github runner files.

**Comment by MSoegtropIMC** [comment]
But I guess you can do a first test using the 32 bit installer - it shouldn't matter for this.

**Comment by jfehrle** [comment]
FYI The artifact files don't appear on the Summary page as described [here](https://github.com/actions/upload-artifact#where-does-the-upload-go), perhaps because some jobs failed.

> As I said you would save you a lot of time (and a bit of CO2) if you would change -extent=x to -extent=i in all github runner files.

Got it.

**Comment by jfehrle** [comment]
I was able to run with my modified patch and verified that the patch was included in the build.

**Comment by MSoegtropIMC** [comment]
@jfehrle : good. Does it work as expected? Should we ask Andrew to test this build?

**Comment by jfehrle** [comment]
No, not ready for that.  The patch still doesn't work at all in platform and I don't see how to fix it.  I'm trying another approach.  I'll let you know.

**Comment by MSoegtropIMC** [comment]
OK. I wonder how this can be. You say it works when installed via opam? What environment do you use? A Coq Platform generated cygwin or something else?

**Comment by jfehrle** [comment]
It only works when I compile it in a developer build locally using dune in a cygwin bash shell.  I do this in a cygwin I installed a while ago, probably from when I was working on the debugger. Does anything from cygwin become part of the CoqIDE executable?  I don't have any good theory at the moment.

**Comment by MSoegtropIMC** [comment]
Coq Platform produces MinGW apps, so it uses the cygwin supplied MinGW cross compiler and includes various cygwin supplied MinGW libraries, but it does (or should) not contain anything from cygwin.

I would say the best development environment for Windows is provided by the cygwin created when installing Coq Platform via the batch file from sources. This batch file first creates a fresh cygwin tailored for Coq development. If it works in there, it should work in Coq Platform.

I remember that a while back you were working on plain cygwin (not MinGW cross), but this is said to be broken for all newer OCaml compilers and not supported - it would be interesting to know if it does work somehow, though - say what OCaml version you are using.

So my main quetsion is: is your coqc and coqide a MinGW app or a cygwin app. Say does coqc understand absolute cygwin paths like /home/ which is then redirected to C:\cygwin_path\home?

**Comment by jfehrle** [comment]
> I would say the best development environment for Windows is provided by the cygwin created when installing Coq Platform via the batch file from sources.

That's what I'm using.

```
$ which ocaml
/home/jfehr/.opam/__coq-platform.2022.04.0~8.15~2022.04/bin/ocaml

$ ocaml --version
The OCaml toplevel, version 4.13.1
```

> I remember that a while back you were working on plain cygwin (not MinGW cross), but this is said to be broken for all newer OCaml compilers and not supported - it would be interesting to know if it does work somehow, though - say what OCaml version you are using.

I use dune to build.  I'm happy to be rid or the old stuff.

> Say does coqc understand absolute cygwin paths like /home/ which is then redirected to C:\cygwin_path\home?

Is this cygwin or MinGW?

```
$ ls -l /home/test.v
-rw-r--r-- 1 jfehr jfehr 0 Oct 20 11:04 /home/test.v

$ coqc /home/test.v  -coqlib _build/default
Error: Can't find file /home/test.v

$ cygpath -w /home/test.v
C:\cygwin64_coq_platform\home\test.v

$ which coqc
/home/jfehr/.opam/__coq-platform.2022.04.0~8.15~2022.04/bin/coqc
```

**Comment by MSoegtropIMC** [comment]
> Is this cygwin or MinGW?

`coqc - where` will tell you. `which coqc` is something the shell does (which is cygwin).

But since you are using a Coq Platform OCaml, it will for sure be MinGW.

The build environment is a MinGW cross environment on cygwin. It is technically similar to building a Windows app on Linux, except that cygwin can easily run MinGW apps like coqc (while Linux can't easily run Windows apps). Just the paths cygwin supplies to MinGW apps must be relative or Windows absolute. Forward slashes are btw. no problem - all Windows apps which don't mess it up explicitly support this.

**Comment by jfehrle** [comment]
> coqc -where will tell you. which coqc is something the shell does (which is cygwin).

Not working for me in Windows, but no point in spending more time on this.

```
$ coqc -where
cannot guess a path for Coq libraries; please use -coqlib option or ensure you have installed the package containing Coq's stdlib (coq-stdlib in OPAM) If you intend to use Coq without a standard library, the -boot -noinit options must be used.

$ coqc testB.v -where -coqlib _build/default
cannot guess a path for Coq libraries; please use -coqlib option or ensure you have installed the package containing Coq's stdlib (coq-stdlib in OPAM) If you intend to use Coq without a standard library, the -boot -noinit options must be used.

$ coqc testB.v -coqlib _build/default
Error: File C:\proj\coq2\_build\default\theories\Init\Prelude.vo has bad
version number 81600 (expected 81591). It is corrupted or was compiled with
another version of Coq.
```

But it does work in WSL:

```
/home/proj/coq2$ coqc -where
/home/jfehrle/.opam/__coq-platform.2022.01.0~8.15~beta1/lib/coq
```

**Comment by jfehrle** [comment]
Done with this

**Comment by MSoegtropIMC** [comment]
> Not working for me in Windows, but no point in spending more time on this.

This has nothing to do with Windows, but with dune. Afaik you either have to install things or use shims when you use dune.

**Comment by jfehrle** [comment]
The shims don't work on Windows because they're shell scripts.  On Linux, you can exec them but Windows won't.  So I use a workaround.  I suggested to Emilio converting the shims to OCaml to fix this, how he eventually does that.

**Pull request closed without merging**
