### PR TITLE
Add package manager installation to Windows README, fix typo

### PR DESCRIPTION
**Pull request by tech189**
Relates to https://github.com/coq/platform/issues/164#issuecomment-1077416199

### CODE REVIEW

**Comment by tech189** [comment]
Maybe these checks which involve building the whole of Coq for every platform shouldn't run if the PR doesn't change the CI / only changes the docs

**Comment by MSoegtropIMC** [comment]
@tech189 : I get few such PRs, so it is not worth the effort. I would suggest that you just create an issue and point me to your fork branch. Most PRs I don't merge anyway but piggy back them cause of the high CI cost, so the PR mechanism is essentially useless.

**Comment by MSoegtropIMC** [comment]
@tech189 : I had a look at (https://community.chocolatey.org/packages?q=Coq) - it appears that they don't use Coq Platform, and if so a rather old version, so we cannot recommend this here.

For scoop I couldn't find a package list on the link you shared, but here (https://rasa.github.io/scoop-directory/by-score.html) I see that it uses Coq Platform. But the license information is wrong. Coq Platform is not LGPL 2.1, but has various licenses (see the package lists). Can you please fix this?

**Comment by tech189** [comment]
(Closing the PR so the checks do not run)

I changed the Chocolatey command to one for winget which has a package for Coq Platform (https://github.com/microsoft/winget-pkgs/blob/master/manifests/c/Coq/CoqPlatform/8.14.1/Coq.CoqPlatform.installer.yaml). Feel free to incorporate my changes to the READMEs yourself, the fork is https://github.com/tech189/platform/tree/patch-1.

As for the license for Scoop's package, since the installer includes non open source software, I'll put that first and then list some of the other licenses like so: `"LGPL-2.1-only, LGPL-3.0-or-later, MIT, GPL-2.0-only, BSD-2-Clause-FreeBSD, CECILL-C, BSD-3-Clause, CECILL-B, ..."`

For `coq-compcert` would you say that "Freeware" or "Proprietary" is an acceptable label?

Is this the correct link to `coq-compcert`'s license: https://github.com/AbsInt/CompCert/blob/master/LICENSE ?

**Comment by MSoegtropIMC** [comment]
The license of coq-compcert is "Proprietary" - it is free to use only in research.

**Comment by tech189** [comment]
I fixed the license in Scoop's Coq package and updated it to the latest version (https://github.com/ScoopInstaller/Main/pull/3548), so you can add my installation instructions to the Windows readme, when you've got the time.

**Pull request closed without merging**
