### PR TITLE
Updating mtac2 version

### PR DESCRIPTION
**Pull request by rtetley**

### CODE REVIEW

**Comment by palmskog** [comment]
@rtetley I don't understand why you need this package in the Platform repo. I've made quite a few improvements to the canonical package that lives in the Coq opam archive: https://github.com/coq/opam/blob/master/released/packages/coq-mtac2/coq-mtac2.1.4%2B8.18/opam

**Comment by rtetley** [comment]
@palmskog there is a list of packages that will be removed from the platform in the tracker issue (#372). To save time I will remove them all in one go once all is done !

**Comment by rtetley** [comment]
Agreed. The pull request was created at the same time as the opam one and I did not think to update it before I merged. I'll be more careful next time :-)

**Comment by rtetley** [comment]
In this instance I'll just open a PR now so to take the improvements into account !

**Comment by palmskog** [comment]
No big issue here really, but maybe we could agree to have a general workflow where Platform packages are first attempted to be added to the Coq opam archive (only), and then if that process stalls after a day for some reason, e.g., due to CI failures, then you add the package here.

**Comment by palmskog** [comment]
By the way @rtetley please ensure you have rights to merge PRs to the Coq opam archive. I try to review and merge fairly quickly, but I may not always be available (and others such as Enrico and Guillaume Melquiond may not be available either). Maybe easiest if you ask Enrico about it.

**Pull request merged**
